version: '3'

services:
  app:
    build: ./.docker/php
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    build: ./.docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
      #- ./.docker/mysql/entrypoint:/docker-entrypoint-initdb.db
    environment:
      - MYSQL_DATABASE=laravel_avancado
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge