version: '3'

services:

  app_laravel:
    build: .docker/php
    container_name: app_laravel
    volumes:
        - ./laravel-es:/var/www
    networks:
        - app-network
    depends_on:
        - elasticsearch_laravel

  nginx_laravel:
    build: .docker/nginx
    container_name: nginx_laravel
    restart: always
    tty: true
    ports:
        - "8000:80"
    volumes:
        - ./laravel-es:/var/www
    networks:
        - app-network
    depends_on:
        - app_laravel

  elasticsearch_laravel:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elasticsearch_laravel
    environment:
      - discovery.type=single-node
    volumes:
      - ./.docker/elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  kibana_laravel:
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - app-network
    depends_on:
      - elasticsearch_laravel

networks:
  app-network:
    driver: bridge